variables:
  DOTNET_VERSION: '9.0'
  NODE_VERSION: '18'
  AZURE_KEY_VAULT_NAME: "eventmgmt-kv"
  AZURE_REGION: "germanywestcentral"

stages:
  - restore
  - build
  - test
  - deploy

before_script:
  - dotnet --version
  - node --version

restore:
  stage: restore
  script:
    - dotnet restore EventManagementSystem.sln

build:
  stage: build
  script:
    - dotnet build EventManagementSystem.sln --configuration Release --no-restore

test:
  stage: test
  script:
    - dotnet test EventManagementSystem.sln --configuration Release --no-build

deploy:
  stage: deploy
  script:
    - echo "Deploying to Azure..."
    # Your deployment scripts here
  only:
    - main